name: PR Comment from file
description: PR Comment from file
inputs:
  path: 
    description: file path
    required: true
runs:
  using: "composite"
  steps:
    - name: "Run script"
      run: |
       echo ${{ inputs.path }}
       cat ${{ inputs.path }}
      shell: bash
    - run: $GITHUB_ACTION_PATH/scr.sh ${{ inputs.path }}
      shell: bash
    - name: Set env
      run: echo "SOMEENV=$(echo lolasdadasdasdasdasdadasdasdadasd | cut -c 1-6)" >> $GITHUB_ENV
      shell: bash
    - name: Test
      run: echo $SOMEENV
      shell: bash
    - uses: actions/github-script@v5
      with:
       script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ SOMEENV }}'
            })