name: PR Comment from file
description: PR Comment from file
inputs:
  path: 
    description: file path
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}