name: PR Comment from file
description: PR Comment from file
inputs:
  path: 
    description: file path
    required: true
  header: 
    description: comment header
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.header }}