name: PR Comment from file
description: PR Comment from file
inputs:
  path: 
    description: file path
    required: true
runs:
  using: "composite"
  steps:
    - name: "Run script"
      run: |
       echo ${{ inputs.path }}
       cat ${{ inputs.path }}
      shell: bash
    - run: $GITHUB_ACTION_PATH/scr.sh ${{ inputs.path }}
      shell: bash