name: PR Comment from file
description: PR Comment from file
inputs:
  path: 
    description: file path
    required: true
runs:
  using: "composite"
  steps:
    - name: "Run script"
      run: |

       echo ${{ inputs.path }}
       cat ${{ inputs.path }}
      shell: bash
    - run: $GITHUB_ACTION_PATH/scr.sh ${{ inputs.path }}
      shell: bash
    - name: Set env
      run: echo "SOMEENV=$(echo lolasdadasdasdasdasdadasdasdadasd | cut -c 1-6)" >> $GITHUB_ENV
      shell: bash
    - name: Test
      id: testing
      run: cat ${{ inputs.path }}
      shell: bash
    - name: Add comment to PR
      env:
          URL: ${{ github.event.issue.comments_url }}
      run: |
         echo  ${{ github.event.issue.comments_url }}
      shell: bash