name: PR Comment from File
author: Alexander Matheson <awmatheson@github.com>
description: Leavess a comment on an open PR based on the contents of a file.
branding:
  icon: 'message-square'  
  color: 'blue'
inputs:
  path: 
    description: file path
    required: true
runs:
  using: "composite"
  steps:
    - id: random-number-generator
      run: |
       echo ${{ inputs.path }}
       cat ${{ inputs.path }}
       cmod 777 ./work.sh
      shell: bash
    - run: work.sh
      shell: bash