name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  file-name:
    description: file with comment
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'